### ISSUE TITLE
add search in app

### ISSUE THREAD

**Issue by haasDev** [lloeki/ex-mode#134]
Would like a search in app feature added similar to how you can use grep in traditional vim.

**Comment by jazzpi** [comment]
What do you mean by a search in app feature? Something like vim's <kbd>/</kbd>? Because that's already implemented in both vim-mode and ex-mode with `:/` as well as in find-and-replace.

If you mean a search through all project files, that's also in find-and-replace (Press <kbd>Ctrl+Shift+F</kbd> or <kbd>Cmd+Shift+F</kbd>)

**Comment by hultberg** [comment]
As we support vim-mode-plus, it has `/` for search.
