### ISSUE TITLE
Swap the current window with the next one

### ISSUE THREAD

**Issue by marius92mc** [lloeki/ex-mode#143]
Hi, 

It would be nice if this command from vim would be supported.
Ctrl-w + x - swap the current window with the next one.

Thank you.

**Comment by LongLiveCHIEF** [comment]
I never used the `ctrl+w` commands in vim, except occasionally to resize (which was in the end easier to just enable mouse mode and drag).

This one could get tricky, because atom's concept of windows and buffers are far different than vim's. 

Can you describe the action you're looking to produce, using examples of your panes in your editor, so that we can be sure we all have the same idea of what this would look like in atom?

**Comment by jazzpi** [comment]
This looks like it should be a feature of vim-mode, not just ex-mode. ex-mode simply adds the command line, vim-mode enables vim-like keybindings.

**Comment by marius92mc** [comment]
I am just referring to the possibility when, after you've opened a new window with split/vsplit, to use "Ctrl-w + x" for swaping those two windows. Because by default it will open the new one in the left half of the screen (in the case of split), and intuitively maybe it would be to have it in the right half.

**Comment by LongLiveCHIEF** [comment]
@marius92mc actually, v0.9.0 allows you to specify this.  We're preparing to release this update any moment now.  You'll be able to go into your settings/preferences screen in atom, click on `ex-mode` settings button, and there'll be a section for controlling split behavior.

It also implements a `:splitright` and `:splitbelow` command.

**Comment by marius92mc** [comment]
@LongLiveCHIEF Ok, thank you very much for the details.
