### ISSUE TITLE
noremap

### ISSUE THREAD

**Issue by ascrookes** [lloeki/ex-mode#170]
First wanted to say thanks for the work on this package, makes Atom so much better.

Is there a way to do mappings? In my vim setup I have mapped ";" & ":" to switch actions which makes getting to the vim command line much quicker/convenient.
In my .vimrc file it is these two lines that accomplish what I'm talking about:
```
noremap ; :
noremap : ;
```

If this isn't possible is it on the roadmap of features to add?

**Comment by jazzpi** [comment]
Is there any reason why you can't just use Atom's keymap feature? Just put this in your `keymap.cson`:

```cson
'atom-text-editor.vim-mode:not(.insert-mode)':
  ':': 'vim-mode:repeat-find'
  ';': 'ex-mode:open'
```

I suppose it would be possible to implement `*noremap` (others would be very hard since parsing recursive bindings would probably be nigh impossible), but I'm not sure if it's really useful in Atom since the stock keymaps are much more powerful and can be bound to any command, not just commands that are bound to keys by default. Also, what would you do if a `noremap` binding conflicted with an Atom binding?
