### ISSUE TITLE
ex-mode future

### ISSUE THREAD

**Issue by romgrk** [lloeki/ex-mode#44]
Hello,

I was wondering about the future of this package. 
I am looking for something that would be more like vim's command bar, wich can be used as both input and output. 
What are your plans about this?

**Comment by lloeki** [comment]
#7 is of interest: it'll definitely need the output part.

As for the input part, I suppose you're making reference to asking user input, such as what (surround.vim) `ysiw<` does?

**Comment by romgrk** [comment]
I was referencing all sorts of input/ouput. In general, are you planning to make this more like a vim's command bar?
If I remember correctly, you started this package out of a general request for a command/ex-mode for vim-mode package, was there specific plans or is it just a base layout? 
I'm asking because I am in the process of starting that kind of package and I was wondering if I should start one or just join in on this. Also I have been watching this package for some time, but I don't see any real progression, are you actively developping this?

**Comment by lloeki** [comment]
> In general, are you planning to make this more like a vim's command bar?

In short, yes. The area that is currently a mere `atom-text-editor[mini]` should grow up into a more full-fledged input area with autocompletion and `wildmenu`. Command output (including errors), should take place in a view at the bottom after the input view disappears (just as in vim). In terms on UX, and at the expense of consistency with Atom, I'm definitely not satisfied as to how errors pop up in the top right since the user has his eyes where the command line used to be (plus he's probably used to vim). Ideally, the input and output system would be available as a service for other packages to consume.

I do have a pretty clear idea of how things turn out but I'm progressing iteratively. I expect that feature to simply "grow out" of #7. As the package grows and stabilises, there is also a dire need for unit tests, which are conspicuously absent. Some cleanup is also in order as I identified areas that need a little refactoring.

> Also I have been watching this package for some time, but I don't see any real progression, are you actively developping this?

Life is being rough on me right now and I can't dedicate as much time to contributions as I'd like, but I have no plans of letting this down (should this be the case, there would be a clear announcement in the `README` and an assorted issue). In the meantime I'm doing my best to fix things up and manage contributions. IOW, you're very welcome to join in :-)

**Comment by romgrk** [comment]
Very well, I'm in then. There are some changes that I already know I would like to make, I'll start threads for each specific issue.

**Comment by lloeki** [comment]
Closing this in favour of other threads. I'd like to focus on stability first and foremost before contemplating any architectural changes.
